name: CI for Java Invoice
on: [push]

jobs:


  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 13, 15 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
    - run: mvn -B install --no-transfer-progress --file pom.xml


  test:
    name: Unit tests
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          
          distribution: 'adopt'
      - name: Test
        run: mvn test
        
  verify:
    name: Checkstye
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          
          distribution: 'adopt'
      - name: Test checkstyle
        run: mvn checkstyle:check

        
    

